IMAGE_NAME = "voight/centos-7.9-x86_64.box"
IMAGE_URL = "http://nexus.voight.org:8081/repository/MachineImages/gold/centos/centos-7.9-x86_64.box"
N = 2

Vagrant.configure("2") do |config|
    config.ssh.username = "centos"
    config.ssh.password = "c4l3nd4R"

    config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
    end

    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.box_url = IMAGE_URL
        master.vm.network "public_network", bridge: "enp6s0", ip: "192.168.137.200"
        master.vm.hostname = "k8s-master"
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "kubernetes-setup/controlplane-playbook.yaml"
            ansible.extra_vars = {
                node_ip: "192.168.137.200",
            }
        end
    end

    (1..N).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.box_url = IMAGE_URL
            node.vm.network "private_network", bridge: "enp6s0", ip: "192.168.137.#{i + 200}"
            node.vm.hostname = "node-#{i}"
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "kubernetes-setup/node-playbook.yaml"
                ansible.extra_vars = {
                    node_ip: "192.168.137.#{i + 200}",
                }
            end
        end
    end
    (N+1..N+1).each do |i|
            config.vm.define "node-#{i}" do |node|
                node.vm.box = IMAGE_NAME
                node.vm.box_url = IMAGE_URL
                node.vm.network "private_network", bridge: "enp6s0", ip: "192.168.137.#{i + 200}"
                node.vm.hostname = "node-#{i}"
        end
    end
end