- name: Install iptables
  yum:
    name: iptables-services.x86_64
  become: true

- name: Stop Firewalld
  systemd:
    name: firewalld
    enabled: no
    state: stopped
  become: true

- name: Start iptables
  service:
    name: iptables
    enabled: yes
    state: started
  become: true

- name: Install docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/
  become: true

- name: Install kubernetes repo
  copy:
    src: files/kubernetes.repo
    dest: /etc/yum.repos.d/
  become: true

- name: Install docker engine
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  become: true

- name: Enable docker
  systemd:
    name: docker
    enabled: yes
    state: started
  become: true

- name: Install curl
  yum:
    name: curl
  become: true

- name: Remove swapfile from /etc/fstab
  become: true
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  become: true
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: IP Forwarding
  copy:
    src: files/k8s.conf
    dest: /etc/sysctl.d/
  become: true

- name: Install Kubernetes binaries
  become: true
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - kubelet
      - kubeadm
      - kubectl
      - nfs-utils

- name: Restart kubelet
  become: true
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted
