- name: Initialize firewalld
  command: {{ item }}
  with_items:
    - firewall-cmd --permanent --add-port=10251/tcp
    - firewall-cmd --permanent --add-port=10255/tcp
    - firewall-cmd --reload
  become: true

- name: Install kubernetes repo
  copy:
    src: files/kubernetes.repo
    dest: /etc/yum.repos.d/
  become: true

- name: Install docker.io
  become: true
  apt: name=docker.io update_cache=yes

- name: Enable docker
  become: true
  service: name=docker state=restarted

- name: Install curl
  become: true
  apt: name=curl

- name: Remove swapfile from /etc/fstab
  become: true
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  become: true
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Update ip forwarding
  become: true
  replace:
    path: /etc/sysctl.conf
    regexp: '^#net.ipv4.ip_forward=1$'
    replace: 'net.ipv4.ip_forward=1'

- name: Update bridge ip6tables
  become: true
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^net.bridge.bridge-nf-call-ip6tables=1'
    insertafter: '^net.ipv4.ip_forward=1$'
    line: 'net.bridge.bridge-nf-call-ip6tables=1'

- name: Update bridge ip4tables
  become: true
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^net.bridge.bridge-nf-call-iptables=1$'
    insertafter: '^net.bridge.bridge-nf-call-ip6tables=1$'
    line: 'net.bridge.bridge-nf-call-iptables=1'

- name: Install Kubernetes binaries
  become: true
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - kubelet
      - kubeadm
      - kubectl

- name: Restart kubelet
  become: true
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted
