- name: Initialize Kubernetes Control Plane
  hosts: all
  tasks:
    - name: Common Tasks
      include_tasks: all-playbook.yaml

    - name: Copy the join command to server location
      copy: src=./tmpfiles/join-command dest=/home/centos/join-command.sh mode=0777

    - name: Join the node to cluster
      command: sh /home/centos/join-command.sh
      become: true
